### ISSUE TITLE
Multiple clients connecting to the same channel

### ISSUE THREAD

**Issue by jhosvr** [probot/smee.io#17] opened 2019-05-19 14:55 UTC
Hi smee team,

I love this service and the idea of it, thank you for your efforts! I found that if multiple clients happen to connect to the same channel id, then all of those clients would receive payloads. Are there any concerns for this? Is there a feature available to lock down a channel ID once one has been generated, so that no two clients can connect at the same time?

I've attached a screenshot where I ran the client locally from my laptop to https://smee.io/conflicttest, then ran the client from a docker container on a remote server, and then sent a test post
![smee-test](https://user-images.githubusercontent.com/25271677/57983918-a9576880-7a24-11e9-9173-918f3c7ec43c.png)
 to see how the channel would behave

**Comment by JasonEtco** [comment] 2019-05-19 15:19
Hey @jhosvr 👋 This is intended behavior. A Smee channel is an EventSource instance, and clients connect to that source to receive events. `smee.io` is one such client.

We've talked a bunch about locking down channels by logging in, but not by locking down specific IDs. Without a way to tie that lockdown to a person, it'd be far too easy to abuse, so I think we'd invest in an authentication mechanism instead. Thanks for bringing it up 🙏 

I'm going to close this out as there are no action items, but I appreciate the question ✨

**Closed by JasonEtco** 2019-05-19 15:19 UTC
